controller_frequency: 10

TrajectoryPlannerROS:
  max_vel_x: 0.5 #0.5
  min_vel_x: 0.1 #0.01
  max_vel_theta: 0.5 #1.5
  min_vel_theta: -0.5
  meter_scoring: true
  min_in_place_vel_theta: 0.25

  acc_lim_theta: 0.25
  acc_lim_x: 0.5
  acc_lim_y: 0.5

  sim_time: 2.0

  vx_samples: 8.0
  vtheta_samples: 20.0

  path_distance_bias: 0.6 #0.6
  goal_distance_bias: 0.8 #0.8
  occdist_scale: 0.02
  xy_goal_tolerance: 0.15
  yaw_goal_tolerance: 0.1
  oscillation_reset_dist: 0.1

  holonomic_robot: false
