map_type: costmap

obstacle_range: 1.0 # 2.0
raytrace_range: 1.0 # 3.0

transform_tolerance: 3.0 # 0.0

footprint: [[-0.21, -0.165], [-0.21, 0.165], [0.21, 0.165], [0.21, -0.165]]
inflation_radius: 0.15 # 0.0
cost_scaling_factor: 5.0

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: rplidar_link, data_type: LaserScan, topic: /scan, marking: true, clearing: true}
